### ISSUE TITLE
How long will the tpl code be open？

### ISSUE THREAD

**Issue by LorcanL** [uulm-mrm/tpl#1]

**Comment by joruof** [comment]
With the initial open-source release the library will be available pretty much indefinitely.

However I'm assuming you were asking *when* the code will be relased:

We are currently working on a cleaned up and useable version of the library.
But given that I'm also currently drowning in engineering work, it may (sadly) require some more time.
Sorry for the inconvenience!

**Comment by feiyuxiaoThu** [comment]
> With the initial open-source release the library will be available pretty much indefinitely.
> 
> However I'm assuming you were asking _when_ the code will be relased:
> 
> We are currently working on a cleaned up and useable version of the library. But given that I'm also currently drowning in engineering work, it may (sadly) require some more time. Sorry for the inconvenience!

So， Now it is 2024...

**Comment by joruof** [comment]
Code is finally online. Sorry again for the delay!
